---
output: github_document
editor_options: 
chunk_output_type: console
---
# Data et code lié à une présentation AFU

## Workshop
Le projet collectif ARCHÉOLOGIE DU FAIT URBAIN (AFU) de l'UMR 7041 ArScAn tient le vendredi 16 décembre 2022 sa cinquième journée d’étude qui a pour sujet [“Faire ou ne pas faire (de) quartier ?”](https://faiturbain.hypotheses.org/journee-du-16-decembre-2022-faire-ou-ne-pas-faire-de-quartier-2)

## Présentation
### Titre
La géographie théorique et quantitative pour étudier les usages du concept de quartier en archéologie

### Résumé
L’intervention a pour objectif de montrer comment la géographie théorique et quantitative est efficace pour nous aider à questionner, voire repenser, la notion de quartier telle qu’appréhendée et saisissable en archéologie. La présentation sera organisée en deux temps, tous deux ponctués d’exemples concrets :

1. on s’intéressera d’abord aux usages du mot « quartier » en archéologie préventive en France à partir d’une étude menée sur les riches métadonnées des rapports de l’INRAP récupérés par web scraping sur portail ARIADNE (voir : [http://portal.ariadne-infrastructure.eu/search](http://portal.ariadne-infrastructure.eu/search)). On verra ici comment l’analyse lexicométrique couplée à l’analyse de la localisation des opérations préventives selon l’occupation du sol permet d’identifier les principaux usages du mot et les formes de conceptualisation sous-jacentes à ces usages.

2. on étudiera ensuite comment les localisations des activités dans la ville permet de percevoir la diversité de ce qui peut « faire quartier ». On se concentrera sur le cas de Paris au 19e siècle, cas récent, mais qui sera ici explicitement utilisé comme laboratoire de réflexions pour des périodes plus anciennes.

### Data

1. Métadonnées rapports de l'INRAP :

* scraping depuis l'API du portail ARIADNE

* CORINE Land Cover (CLC) millésimes 2006 et 2018, [http://www.statistiques.developpement-durable.gouv.fr/corine-land-cover-0](http://www.statistiques.developpement-durable.gouv.fr/corine-land-cover-0)
